# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChangeWishListItem.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43hangeWishListItem.proto\"m\n\x17\x43SChangeWishListItemReq\x12\x14\n\x0c\x61\x64\x64_item_ids\x18\x01 \x03(\r\x12\x14\n\x0c\x64\x65l_item_ids\x18\x02 \x03(\r\x12\x12\n\nadd_source\x18\x03 \x03(\t\x12\x12\n\ndel_source\x18\x04 \x03(\t\"f\n\x17\x43SChangeWishListItemRes\x12\x1c\n\x14success_add_item_ids\x18\x01 \x03(\r\x12\x1c\n\x14success_del_item_ids\x18\x02 \x03(\r\x12\x0f\n\x07message\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChangeWishListItem_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CSCHANGEWISHLISTITEMREQ']._serialized_start=28
  _globals['_CSCHANGEWISHLISTITEMREQ']._serialized_end=137
  _globals['_CSCHANGEWISHLISTITEMRES']._serialized_start=139
  _globals['_CSCHANGEWISHLISTITEMRES']._serialized_end=241
# @@protoc_insertion_point(module_scope)
